name: Scratchpad

on:
  schedule:
    - cron: '45 11 * * *'
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      runtimeImage:
        description: 'Name/tag of the base runtime image'
        required: false
      base64EncodedEnvVars:
        # We are doing this because there is a max of 10 inputs on GH Actions
        description: 'Env vars (one per line) encoded with base64'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check env
        run: |
          echo Env: '${{github.event.inputs.runtimeImage}}'

      - name: Set runtime image override variable
        if: ${{github.event.inputs.runtimeImage}}
        run: |
          # Set the system property to choose a different image when running the tests
          echo ${{github.event.inputs.runtimeImage}}
          TMP="-Dimage.name.wildfly.runtime=${{github.event.inputs.runtimeImage}}"
          echo "RUNTIME_IMAGE_OVERRIDE=${TMP}" >> $GITHUB_ENV
          
      - name: Unencode env vars for the tests
        if: ${{github.event.inputs.base64EncodedEnvVars}}
        run: |
          echo ${{github.event.inputs.base64EncodedEnvVars}} > encodedVars.txt
          base64 --decode encodedVars.txt > envVars.env
          
          echo Decoded vars:
          cat envVars.env
          
          while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done < envVars.env
          

      - name: Next step
        run: |
          echo Override: ${RUNTIME_IMAGE_OVERRIDE}
          echo Kafka Host: ${KAFKA_HOST}

      ########################################################################################
      # Use this step to read environment variables required for your manual test, and set
      # an env var to trigger a later step to run the test, as well as any env vars for
      # maven options etc.
      - name: Check which manual jobs to run and set env vars
        run: |
          # RHOSAK_PARAMETERS
          if [ -v KAFKA_HOST ]; then
            if [ -v RHOAS_CLIENT_ID ]; then
              if [ -v RHOAS_CLIENT_SECRET ]; then
                TMP="-Pmanual-rhosak -pl tests/manual/rhosak -Dwildfly.cloud.test.manual.rhoas.kafka.host=$KAFKA_HOST -Dwildfly.cloud.test.manual.rhoas.client.id=$RHOAS_CLIENT_ID -Dwildfly.cloud.test.manual.rhoas.client.secret=RHOAS_CLIENT_SECRET"
                # This stores the env var for use in later steps
                echo "RHOSAK_PARAMETERS=${TMP}" >> $GITHUB_ENV
                echo "$TMP"
              fi
            fi
          fi

      - name: RHOSAK tests
        if: ${{ env.RHOSAK_PARAMETERS }}
        run: |
          echo "We are running RHOSAK tests"
          mvn -B clean install 
