name: WildFly Cloud Tests

on:
  schedule:
    - cron: '45 11 * * *'
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      runtimeImage:
        description: 'Name/tag of the base runtime image'
        required: false
      base64EncodedEnvVars:
        # We are doing this because there is a max of 10 inputs on GH Actions
        description: 'Env vars (one per line) encoded with base64'
        required: false

jobs:
  wildfly-runtime-jdk11:
    if: ${{!github.event.inputs.runtimeImage}}
    uses: ./.github/workflows/wildfly-cloud-tests-callable.yml
    with:
      runtimeImage: quay.io/wildfly/wildfly-runtime-jdk11:latest
  wildfly-runtime-jdk17:
    if: ${{!github.event.inputs.runtimeImage}}
    uses: ./.github/workflows/wildfly-cloud-tests-callable.yml
    with:
      runtimeImage: quay.io/wildfly/wildfly-runtime-jdk17:latest
  wildfly-runtime-jdk11-multi-arch:
    if: ${{!github.event.inputs.runtimeImage}}
    uses: ./.github/workflows/wildfly-cloud-tests-callable.yml
    with:
      runtimeImage: quay.io/wildfly-snapshots/wildfly-runtime-jdk11-multi-arch:latest
  wildfly-custom-image:
    if: ${{github.event.inputs.runtimeImage}}
    uses: ./.github/workflows/wildfly-cloud-tests-callable.yml
    with:
      runtimeImage: ${{github.event.inputs.runtimeImage}}
      base64EncodedEnvVars: ${{github.event.inputs.base64EncodedEnvVars}}
